# ------------------------------------------------------- #
#      Please do not modify this autogenerated file.      #
#  Use  >> build.sh --publish <<  to update its content.  #
# ------------------------------------------------------- #

OPENSSL_FETCH_VERSION='1.1.1g'
OPENSSL_FETCH_ANDROID_URL='https://github.com/wultra/cc7/releases/download/0.3.0/openssl-1.1.1g-android.tar.gz'
OPENSSL_FETCH_ANDROID_HASH='7a3ff0e7d50f0bc6097a1aace2d5d5dda508185ddcf120a35b3d9c5f18533d0a'
OPENSSL_FETCH_APPLE_URL='https://github.com/wultra/cc7/releases/download/0.3.0/openssl-1.1.1g-apple.tar.gz'
OPENSSL_FETCH_APPLE_HASH='aaf4da50e954b92db886be59a4d600cc9c785c67ce29494ed537b0acff4ae566'
OPENSSL_FETCH_APPLE_XCFW_URL='https://github.com/wultra/cc7/releases/download/0.3.0/openssl-1.1.1g.xcframework.zip'
OPENSSL_FETCH_APPLE_XCFW_HASH='5d4c39f779ec6b1e56524689b30baffc0fcf16c90e8f9d12c75703edd772dc99'
